### ISSUE TITLE
Scheduled link check should not run on forks

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#799]
So far, contributors have created forks of the repository in order to contribute, not to host an alternative instance. As such, only the [Test](https://github.com/publiccodenet/standard/actions/workflows/test.yml) workflow makes sense. The other workflows, especially the [Scheduled link check](https://github.com/publiccodenet/standard/actions/workflows/link-check.yml), should not run on forks.

**Comment by ericherman** [comment]
I don't see a way to enable a workflow only if the repository matches.
One idea I have is to do this from inside the [script](https://github.com/publiccodenet/standard/blob/develop/script/test-with-link-check.sh) itself, by adding something like this near the top:

```bash
# if GITHUB_REPOSITORY is not set (e.g.: while developing on your laptop) it will continue
# but if GITHUB_REPOSITORY is set to another repository, it will exit early
if [ "_${GITHUB_REPOSITORY}_" != "__" ] && [ "$GITHUB_REPOSITORY" != "publiccodenet/standard" ]; then
        echo "skipping run for GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
        exit 0
fi
```

Is there a better way?

**Comment by rgs** [comment]
Maybe try to have a first step or a first job that fails if the repository does not match?
Here's an untested example with a check job (but if you have only one job you could include this as a first step).

```yaml
jobs:
  check-repository:
    steps:
      - if: ${{ github.repository != "publiccodenet/standard" }}
        run: exit 1
  next-job-1:
    needs: check-repository
    ...
```

(note that the failing value for `exit` is of course non-zero, this is shell)

**Comment by ericherman** [comment]
Thank you for the idea, @rgs

I think it will still spam owners of forks that "their" job failed, which would be a key thing to avoid.

**Comment by rgs** [comment]
Good remark. In this case I'd just include an `if:` on top of each job:
```yaml
jobs:
  do-something:
    if: ${{ github.repository == "publiccodenet/standard" }}
    steps:
      - ...
```
Redundant (if you have several jobs), but should work.
